apiVersion: v2
name: onecx-product-store-svc
version: 0.0.0
appVersion: 0.0.0
description: Onecx product store service
keywords:
  - tenant
sources:
  - https://github.com/onecx/onecx-product-store-svc
maintainers:
  - name: Tkit Developer
    email: tkit_dev@1000kit.org
dependencies:
  - name: helm-quarkus-app
    alias: app
    version: 0.41.0
    repository: oci://ghcr.io/onecx/charts